Update Lesson 4 homework answer
viettrung9012/python-codeacademy-sg pull request #40
Opened 2018-07-03 06:54 UTC by YuelinYang

- [ ] This PR contains only information intended for public view

To view this PR's branch in binder:
```
https://mybinder.org/v2/gh/viettrung9012/python-codeacademy-sg/<branch>?urlpath=lab
```

2018-07-03 07:02 UTC, kennytean commented on Homework/Solutions/Lesson4.ipynb
> +    "## Some Takehome Exercises (Opitonal) ---- Solutions\n",
Optional

2018-07-03 09:36 UTC, FabienLauf requested changes

2018-07-03 09:36 UTC, FabienLauf commented on Homework/Solutions/Lesson4.ipynb
> +    "Participants 3's steps until day 7: 139920\n",
"Participant" without "s"

2018-07-03 09:36 UTC, FabienLauf commented on Homework/Solutions/Lesson4.ipynb
> +    "Participants 3's steps until day 7 : 139920\n",
"Participant" without "s"

2018-07-03 09:36 UTC, FabienLauf commented on Homework/Solutions/Lesson4.ipynb
> +    "Participants 3 on day 25 walked 408190\n",
"Participant" without "s"

2018-07-03 09:36 UTC, FabienLauf commented on Homework/Solutions/Lesson4.ipynb
> +    "                    print(\"Participants \" + str(index) + \" on day \" + str(i) + \" walked \" + str(total_steps))"
"Participant" without "s"

2018-07-04 02:09 UTC, FabienLauf approved these changes

2018-07-04 02:09 UTC, merged